### PR TITLE
Made it compatible with Android 8.0

### PR DESCRIPTION
**Pull request by kvsjxd**

### CODE REVIEW

**Comment by blurpy** [comment]
Thank you for the pull request!

I'm without access to my main development machine at the moment, but I will merge this when I've tested it.

A question about the dependencies. I split tests into src/test and src/androidTest and the dependencies into testCompile and androidTestCompile so it was easier to know what they were for. Now they are all androidTestImplementation. Did you have issues using testImplementation where it used to be testCompile?

**Comment by kvsjxd** [comment]
I'm having no issues using testImplementation where it used to be testCompile.

**Comment by blurpy** [comment]
OK, could you make a new commit with that change?

**Comment by kvsjxd** [comment]
Yes

**Pull request closed without merging**
